remote_theme: thuhcsi/slate
title: Enhancing Word-Level Semantic Representation via Dependency Structure for Expressive Text-to-Speech Synthesis
description: Submitted to Interspeech 2022.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
